// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 11/02/2026, 10:01:42
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["C:/Users/Willian001/Projeto-Freelances/Santos Games/Front-PortalSantosTech/src/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Willian001/Projeto-Freelances/Santos Games/Front-PortalSantosTech/src/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Willian001/Projeto-Freelances/Santos Games/Front-PortalSantosTech/src/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Willian001/Projeto-Freelances/Santos Games/Front-PortalSantosTech/src/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Willian001/Projeto-Freelances/Santos Games/Front-PortalSantosTech/src/plugins/**/*.{js,ts,mjs}","C:/Users/Willian001/Projeto-Freelances/Santos Games/Front-PortalSantosTech/src/composables/**/*.{js,ts,mjs}","C:/Users/Willian001/Projeto-Freelances/Santos Games/Front-PortalSantosTech/src/utils/**/*.{js,ts,mjs}","C:/Users/Willian001/Projeto-Freelances/Santos Games/Front-PortalSantosTech/src/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Willian001/Projeto-Freelances/Santos Games/Front-PortalSantosTech/src/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Willian001/Projeto-Freelances/Santos Games/Front-PortalSantosTech/src/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Willian001/Projeto-Freelances/Santos Games/Front-PortalSantosTech/src/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;